name: gdsc_nu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  accordion: ^2.5.1
  animated_toggle_switch: ^0.6.1
  auth_buttons: ^1.0.1+4
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  flutter_spinkit: ^5.1.0
  flutter_splash_screen: ^1.0.0+6
  flutterflow_widgets: ^0.0.38
  font_awesome: ^5.10.1
  font_awesome_flutter: ^10.4.0
  getwidget: ^3.0.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  http: ^0.13.5
  provider: ^6.0.5
  speech_to_text: ^6.1.1
  timeline_tile: ^2.0.0
  video_player: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/


flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#1A1F24"
  color_dark: "#1A1F24"
  image: assets/images/GDSC NIIT UNIVERISTY .png
  image_dark: assets/images/GDSC NIIT UNIVERISTY .png

  android_12:
    image: assets/images/GDSC NIIT UNIVERISTY .png
    icon_background_color: "#1A1F24"
    image_dark: assets/images/GDSC NIIT UNIVERISTY .png
    icon_background_color_dark: "#1A1F24"

  web: false

